services:
  gamevault-backend:
    container_name: gamevault-backend
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    environment:
      DB_SYSTEM: "SQLITE"
    volumes:
      - ${APP_DATA_DIR}/games:/files
      - ${APP_DATA_DIR}/media:/media
      - ${APP_DATA_DIR}/db:/db
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network
    labels: # Use your editors search and replace feature to replace all instances of "gamevault-backend" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.gamevault-backend-web-redirect.redirectscheme.scheme: https
      traefik.http.services.gamevault-backend.loadbalancer.server.port: 8443 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.gamevault-backend-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.gamevault-backend-insecure.entrypoints: web
      traefik.http.routers.gamevault-backend-insecure.service: gamevault-backend
      traefik.http.routers.gamevault-backend-insecure.middlewares: gamevault-backend-web-redirect
      # Websecure
      traefik.http.routers.gamevault-backend.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.gamevault-backend.entrypoints: websecure
      traefik.http.routers.gamevault-backend.service: gamevault-backend
      traefik.http.routers.gamevault-backend.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.gamevault-backend-local-insecure.rule: Host(`gamevault-backend.${LOCAL_DOMAIN}`)
      traefik.http.routers.gamevault-backend-local-insecure.entrypoints: web
      traefik.http.routers.gamevault-backend-local-insecure.service: gamevault-backend
      traefik.http.routers.gamevault-backend-local-insecure.middlewares: gamevault-backend-web-redirect
      # Local domain secure
      traefik.http.routers.gamevault-backend-local.rule: Host(`gamevault-backend.${LOCAL_DOMAIN}`)
      traefik.http.routers.gamevault-backend-local.entrypoints: websecure
      traefik.http.routers.gamevault-backend-local.service: gamevault-backend
      traefik.http.routers.gamevault-backend-local.tls: true
      runtipi.managed: true
