version: "3.7"
services:
  gamevault-backend:
    container_name: gamevault-backend
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network
    environment:
      DB_SYSTEM: "SQLITE"
    volumes:
      - ${APP_DATA_DIR}/games:/files
      - ${APP_DATA_DIR}/games:/media
      - ${APP_DATA_DIR}/games:/db
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.gamevault-backend-web-redirect.redirectscheme.scheme: https
      traefik.http.services.gamevault-backend.loadbalancer.server.port: 8000
      # Web
      traefik.http.routers.gamevault-backend-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.gamevault-backend-insecure.entrypoints: web
      traefik.http.routers.gamevault-backend-insecure.service: gamevault-backend
      traefik.http.routers.gamevault-backend-insecure.middlewares: gamevault-backend-web-redirect
      # Websecure
      traefik.http.routers.gamevault-backend.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.gamevault-backend.entrypoints: websecure
      traefik.http.routers.gamevault-backend.service: gamevault-backend
      traefik.http.routers.gamevault-backend.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.gamevault-backend-local-insecure.rule: Host(`gamevault-backend.${LOCAL_DOMAIN}`)
      traefik.http.routers.gamevault-backend-local-insecure.entrypoints: web
      traefik.http.routers.gamevault-backend-local-insecure.service: gamevault-backend
      traefik.http.routers.gamevault-backend-local-insecure.middlewares: gamevault-backend-web-redirect
      # Local domain secure
      traefik.http.routers.gamevault-backend-local.rule: Host(`gamevault-backend.${LOCAL_DOMAIN}`)
      traefik.http.routers.gamevault-backend-local.entrypoints: websecure
      traefik.http.routers.gamevault-backend-local.service: gamevault-backend
      traefik.http.routers.gamevault-backend-local.tls: true
      runtipi.managed: true
